kind: pipeline
type: kubernetes
name: postgres 

steps:
  - name: docker-build-push-backend
    image: registry.cloudclusters.net/cloudclusters/plugins-docker:linux-amd64
    pull: always
    settings:
      repo: registry.cloudclusters.net/cloudclusters/postgrestestci
      registry: registry.cloudclusters.net
      debug: true
      pvtag: true
      autotag: false
